version: "3.9"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    expose:
      - 5432
    ports:
      - 5432:5432
