services:
  postgres:
    image: "postgis/postgis:15-3.5-alpine"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    expose:
      - 5432
    ports:
      - 5432:5432
