// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBREDH7txo88wPpZxAiYRgA_GSLgQ15o',
    appId: '1:567748302140:web:dcceb10dd4f57858523a39',
    messagingSenderId: '567748302140',
    projectId: 'skripsi-e8cfb',
    authDomain: 'skripsi-e8cfb.firebaseapp.com',
    storageBucket: 'skripsi-e8cfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANuMR8AbV6l88m3bXVBLLc0ebXZ7eHzF0',
    appId: '1:567748302140:android:258d2e0327fa1dba523a39',
    messagingSenderId: '567748302140',
    projectId: 'skripsi-e8cfb',
    storageBucket: 'skripsi-e8cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBiQNkRxHtnLcWQEtxe4_k3ZC7PsMV4FA',
    appId: '1:567748302140:ios:e0a2a7b971794bd4523a39',
    messagingSenderId: '567748302140',
    projectId: 'skripsi-e8cfb',
    storageBucket: 'skripsi-e8cfb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBiQNkRxHtnLcWQEtxe4_k3ZC7PsMV4FA',
    appId: '1:567748302140:ios:e0a2a7b971794bd4523a39',
    messagingSenderId: '567748302140',
    projectId: 'skripsi-e8cfb',
    storageBucket: 'skripsi-e8cfb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSBREDH7txo88wPpZxAiYRgA_GSLgQ15o',
    appId: '1:567748302140:web:6133784de9c00179523a39',
    messagingSenderId: '567748302140',
    projectId: 'skripsi-e8cfb',
    authDomain: 'skripsi-e8cfb.firebaseapp.com',
    storageBucket: 'skripsi-e8cfb.firebasestorage.app',
  );
}